[package]
name = "jass_parser"
version = "0.1.0"
authors = ["Samuel Moriarty <insomnia.array@gmail.com>"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.17.2"
codespan = "0.6.0"
byteorder = "*"

[build-dependencies]
lalrpop = "0.17.2"